/**
 * Port of Pulse's `UsageBubbleShape` (Sources/Pulse/Panel/UsageBubbleShape.swift)
 * — the details card's outline: rounded body and pointer as ONE path.
 *
 * These used to be two views side by side in a stack — a rounded rectangle and
 * a separate pointer nudged into place with padding. Switching providers
 * changes the card's height and the pointer's target at the same time, and two
 * views animating separately don't stay in step: the tail visibly comes away
 * from the card mid-transition. Drawing both as one shape makes that
 * impossible, since there is nothing left to fall out of sync.
 */

import type { PanelEdge } from './berthShape'

/** Which of the outline to draw. Glass draws the body and the tail separately and lets the system fuse them. */
export type BubblePart = 'whole' | 'body' | 'tail'

export interface Rgb {
  r: number
  g: number
  b: number
}

/** Superellipse exponent. 2 is a plain circle; 4 lands close to Apple's squircle. */
const SQUIRCLE_EXPONENT = 4
/** Enough segments that the sampled curve stays sub-pixel smooth at card sizes. */
const CORNER_SAMPLE_COUNT = 48

const n = (v: number) => (Math.round(v * 1000) / 1000).toString()

/**
 * Where the two control points of each flank sit, as fractions of `reach` along
 * the tail and of `sweep` across it.
 *
 * With round ends the first control point sits **on the card's edge** — `along`
 * is zero — so the flank leaves the card along that edge and bends out to the
 * tip, the way the rail's flare leaves the screen edge.
 *
 * Softened ends (the default) keep the shipped tail, whose flanks leave the
 * edge at an angle. The original is candid that this "puts a crease either side
 * of the base, which is what makes it read as a triangle stuck on rather than
 * grown out of the card — but it is the tail the rest of that style was drawn
 * against."
 */
const TAIL_CONTROLS_ROUND = { nearAlong: 0, nearAcross: 0.5, farAlong: 0.55, farAcross: 0.22 }
const TAIL_CONTROLS_SOFT = { nearAlong: 0.24, nearAcross: 0.44, farAlong: 0.55, farAcross: 0.24 }

interface Vec {
  dx: number
  dy: number
}

/**
 * One quarter of a superellipse, as line segments.
 *
 * SwiftUI draws this as `.continuous` for rounded rectangles, and the original
 * uses it for the card body so the card's corners belong to the same family of
 * curves as the rail's. The outline is generated by hand here, so it is sampled
 * the same way `DockBerthShape.appendCorner` samples it.
 */
function superellipseCorner(
  center: { x: number; y: number },
  radius: number,
  from: Vec,
  to: Vec,
): Array<{ x: number; y: number }> {
  if (radius <= 0) return []

  const points: Array<{ x: number; y: number }> = []
  for (let step = 1; step <= CORNER_SAMPLE_COUNT; step++) {
    const t = (step / CORNER_SAMPLE_COUNT) * (Math.PI / 2)
    // |x/r|^n + |y/r|^n = 1, in its parametric form.
    const along = Math.pow(Math.cos(t), 2 / SQUIRCLE_EXPONENT)
    const across = Math.pow(Math.sin(t), 2 / SQUIRCLE_EXPONENT)
    points.push({
      x: center.x + radius * (from.dx * along + to.dx * across),
      y: center.y + radius * (from.dy * along + to.dy * across),
    })
  }
  return points
}

/** A rounded rectangle whose corners are quarter superellipses (`.continuous`). */
export function squircleRect(x: number, y: number, w: number, h: number, radius: number): string {
  const r = Math.max(0, Math.min(radius, Math.min(w, h) / 2))
  if (r <= 0) {
    return `M ${n(x)} ${n(y)} L ${n(x + w)} ${n(y)} L ${n(x + w)} ${n(y + h)} L ${n(x)} ${n(y + h)} Z`
  }

  const parts: string[] = [`M ${n(x + r)} ${n(y)}`]

  // Traversed clockwise, the same winding the tail is given below.
  const corner = (cx: number, cy: number, from: Vec, to: Vec) => {
    for (const p of superellipseCorner({ x: cx, y: cy }, r, from, to)) {
      parts.push(`L ${n(p.x)} ${n(p.y)}`)
    }
  }

  parts.push(`L ${n(x + w - r)} ${n(y)}`)
  corner(x + w - r, y + r, { dx: 0, dy: -1 }, { dx: 1, dy: 0 })
  parts.push(`L ${n(x + w)} ${n(y + h - r)}`)
  corner(x + w - r, y + h - r, { dx: 1, dy: 0 }, { dx: 0, dy: 1 })
  parts.push(`L ${n(x + r)} ${n(y + h)}`)
  corner(x + r, y + h - r, { dx: 0, dy: 1 }, { dx: -1, dy: 0 })
  parts.push(`L ${n(x)} ${n(y + r)}`)
  corner(x + r, y + r, { dx: -1, dy: 0 }, { dx: 0, dy: -1 })

  parts.push('Z')
  return parts.join(' ')
}

export interface BubblePathOptions {
  width: number
  height: number
  /** Which side the pointer leaves from — the side facing the rail. */
  edge: PanelEdge
  /**
   * Centre of the pointer along the side it leaves from: measured down from the
   * shape's top edge for a card beside the rail, and in from its leading edge
   * for one hanging below it.
   */
  pointerCenter: number
  cornerRadius: number
  pointerWidth: number
  pointerHeight: number
  /** Which of the outline to draw. */
  part?: BubblePart
  /** `AppSettings.usesRoundEnds`. Picks the shipped tail or the round-ended one. */
  usesRoundEnds?: boolean
}

const isVertical = (edge: PanelEdge) => edge === 'left' || edge === 'right'
const isLeft = (edge: PanelEdge) => edge === 'left'

/**
 * The card's outline, always generated facing the rail on the RIGHT; callers
 * place it with `bubbleTransform`.
 *
 * A card below a top rail is the same silhouette given a quarter turn. Drawn in
 * a rect laid on its side and rotated back, so there is one copy of the
 * geometry — and because a rotation is not a reflection, the winding the body
 * and the tail have to share survives it. **Mirroring would reverse the tail
 * and punch a gap between them, which is exactly what the left edge did once**:
 * the two are separate subpaths filled as one shape, and under the non-zero
 * fill rule opposite windings cancel where they overlap.
 */
export function bubblePath(options: BubblePathOptions): string {
  const { width, height, edge, pointerCenter, cornerRadius, pointerWidth, pointerHeight } = options
  const part = options.part ?? 'whole'
  const usesRoundEnds = options.usesRoundEnds ?? false

  if (!isVertical(edge)) {
    // The canonical rect is this one laid on its side.
    return facingSideways({
      width: height,
      height: width,
      pointerCenter,
      cornerRadius,
      pointerWidth,
      pointerHeight,
      part,
      usesRoundEnds,
      edge: 'right',
    })
  }

  return facingSideways({
    width,
    height,
    pointerCenter,
    cornerRadius,
    pointerWidth,
    pointerHeight,
    part,
    usesRoundEnds,
    edge,
  })
}

interface SidewaysOptions {
  width: number
  height: number
  edge: PanelEdge
  pointerCenter: number
  cornerRadius: number
  pointerWidth: number
  pointerHeight: number
  part: BubblePart
  usesRoundEnds: boolean
}

function facingSideways(o: SidewaysOptions): string {
  const left = isLeft(o.edge)

  // The pointer lives in a strip along the rail-facing side; the body fills
  // what's left.
  const bodyX = left ? o.pointerWidth : 0
  const bodyW = Math.max(o.width - o.pointerWidth, 0)

  const body = squircleRect(bodyX, 0, bodyW, o.height, o.cornerRadius)
  const tail = pointerPath(o, bodyX, bodyW)

  if (o.part === 'tail') return tail
  if (o.part === 'body') return body
  return `${body} ${tail}`
}

/**
 * The tail, as a subpath overlapping the body's edge so the two read as a
 * single silhouette once filled.
 */
function pointerPath(o: SidewaysOptions, bodyX: number, bodyW: number): string {
  const left = isLeft(o.edge)
  const half = o.pointerHeight / 2

  // Keep the tail clear of the rounded corners, and inside the card even when
  // the caller asks for something out of range.
  const centre = Math.min(
    Math.max(o.pointerCenter, o.cornerRadius + half),
    Math.max(o.height - o.cornerRadius - half, o.cornerRadius + half),
  )

  const baseX = left ? bodyX : bodyX + bodyW
  const tipX = left ? 0 : o.width
  const reach = tipX - baseX

  // Traverse the tail in the direction that winds the same way as the body's
  // rounded rectangle.
  const sweep = left ? -half : half

  const c = o.usesRoundEnds ? TAIL_CONTROLS_ROUND : TAIL_CONTROLS_SOFT

  const parts: string[] = []
  parts.push(`M ${n(baseX)} ${n(centre - sweep)}`)

  parts.push(
    `C ${n(baseX + reach * c.nearAlong)} ${n(centre - sweep * c.nearAcross)}, ` +
      `${n(baseX + reach * c.farAlong)} ${n(centre - sweep * c.farAcross)}, ` +
      `${n(tipX)} ${n(centre)}`,
  )

  parts.push(
    `C ${n(baseX + reach * c.farAlong)} ${n(centre + sweep * c.farAcross)}, ` +
      `${n(baseX + reach * c.nearAlong)} ${n(centre + sweep * c.nearAcross)}, ` +
      `${n(baseX)} ${n(centre + sweep)}`,
  )

  // Bite back into the body so the join is covered by the fill rather than
  // leaving a seam along the edge.
  parts.push(`L ${n(baseX - reach * 0.08)} ${n(centre + sweep)}`)
  parts.push(`L ${n(baseX - reach * 0.08)} ${n(centre - sweep)}`)
  parts.push('Z')

  return parts.join(' ')
}

/**
 * Placement for a card hanging below a top rail.
 *
 * A **rotation, not a reflection** — the same rule the rail's own outline
 * follows, and for the same reason: a reflection reverses the winding and the
 * body and tail would cancel where they overlap.
 */
export function bubbleTransform(edge: PanelEdge, height: number): string | undefined {
  if (isVertical(edge)) return undefined
  return `matrix(0,-1,1,0,0,${n(height)})`
}

/** The `w × h` box the canonical (rail-on-the-right) path is drawn into. */
export function bubbleCanvas(
  edge: PanelEdge,
  width: number,
  height: number,
): { width: number; height: number } {
  return isVertical(edge) ? { width, height } : { width: height, height: width }
}
